### ISSUE TITLE
Can't install from .deb file

### ISSUE THREAD

**Issue by exquest** [sentinel-official/sentinel#12]
using the command: `sudo dpkg -i sentinel-desktop-app_0.1.0_amd64.deb`

I get:

dpkg-deb: error: `sentinel-desktop-app_0.1.0_amd64.deb' is not a debian format archive
dpkg: error processing archive sentinel-desktop-app_0.1.0_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 sentinel-desktop-app_0.1.0_amd64.deb

**Comment by ironman0x7b2** [comment]
It's because we built Debian package only for 64 bit version.
