### ISSUE TITLE
Windows 10 endless payment loop on trying to connect VPN

### ISSUE THREAD

**Issue by tekspirit** [sentinel-official/sentinel#51]
With today's version, alpha-0.0.32, when I go to the VPN list and select one, it asks me to pay (xxx cents).  I do so, check the confirmation, and after 25 confirmations, try to connect.  I click the same connection point and it says "you must pay before you connect" and requests another payment.  It does this endlessly and never makes a VPN connection.  OpenVPN is running.

**Comment by fabulous345** [comment]
There was some problem faced in server side. Now its solved. It will be working fine from next release.Thanks.
