### ISSUE TITLE
Airdrop testing issues

### ISSUE THREAD

**Issue by CryptoEEra** [sentinel-official/sentinel#53]
I got to the step where I have to pay 100 tokens for the vpn to connect, but when I press "connect", that's the error that I get: 
Install Dependencies
OpenVPN Not Installed.Install here https://openvpn.net/index.php/open-source/downloads.html.copy
Please install openvpn in default folder.(C:\\Program Files)

Any help???

**Comment by riotcs** [comment]
Yes, you need to install openvpn first. Please follow the setup guide from here https://github.com/sentinel-official/sentinel/tree/master/wallet
